### ISSUE TITLE
Link is down 

### ISSUE THREAD

**Issue by prasad47** [MobileFirst-Platform-Developer-Center/CustomDirectUpdate#1]
hi,
 This link is down 
https://mobilefirstplatform.ibmcloud.com/tutorials/en/foundation/8.0/using-the-mfpf-sdk/direct-update/ 
this link is down with 404 error can you please share the working link 

Thanks,
Prasad

**Comment by vivinkrishnan** [comment]
@prasad47 

Refer:

https://mobilefirstplatform.ibmcloud.com/tutorials/en/foundation/8.0/application-development/direct-update/
